### PR TITLE
- Added description file

### LINKED ISSUE #3: Adding prerequisites
Adding a prerequisites section that includes stuff such as definitions and key terms as refreshers will enhance the user's experience with the app.

### PR DESCRIPTION
**Pull request by shravanisamala**
- Fixed top three buttons
- Added titles for two tabs
- Added copyright info

### CODE REVIEW

**Review by Maxinewsu — DISMISSED** [review]
**Recommended Priority: High**
- The two issues are unaddressed.
- Add a prerequisite page to explain the basic concept of ANOVA model better.
- Add descriptions when building models, giving definitions of each concepts. (main effects, replicates)
- Add descriptions beside the general ANOVA model explaining what each letters mean. (e.g. i,j,k,t)
- Provide more examples to help practice.
- The drag button is not sensitive.
- The font is not consistent.
- There are too many white spaces at the bottom of each page.

**Review by ymy5178 — COMMENTED** [review]
Recommended Priority: Urgent

Everything is good! just a small problem in readme

1. docs file should be built in the file which includes readme, license and screenshot.

**Review by JingFu1 — CHANGES_REQUESTED** [review]
Recommended Priority: Urgent

Lack of citation in overview page.

**Review by JingFu1 — CHANGES_REQUESTED** [review]
When I ran the app, it showed "
<simpleError in parse(text = value): <text>:8:0: unexpected end of input
6: person(given = "Wanyi", family = "Su", email = "wbs5152@psu.edu", role = c("ctb"))
7: )
  ^>
"
Recommended Priority: High

**Comment by Maxinewsu** [comment]
@JingFu1 @ymy5178 Please re-review this app since I made some changes according to Jing's comments. Many thanks!

**Review by ymy5178 — DISMISSED** [review]
I believe it is good to go

**Review by JingFu1 — DISMISSED** [review]

**Review by neilhatfield — APPROVED** [review]
Approving the changes made earlier.

**Pull request merged**
